default: &default
  adapter: postgresql
  encoding: unicode
  user: postgresql
  password: postgresql
  host: localhost

  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: contacts_development


test:
  <<: *default
  database: contacts_test

production:
  <<: *default
  database: contacts_production
  username: contacts_gateway
  password: <%= ENV["GATEWAY_DATABASE_PASSWORD"] %>